In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
path = "../dataset/functioninvocationtrace/AzureFunctionsInvocationTraceForTwoWeeksJan2021.txt"

In [3]:
df = pd.read_csv(path)

In [4]:
df['arrival_time'] = df['end_timestamp'] - df['duration']
df.sort_values(by=['arrival_time'], inplace=True, ascending=True)
df['arrival_time_fix'] = df['arrival_time'] - df['arrival_time'].iloc[0]
df.sort_values(by=['arrival_time_fix'], inplace=True, ascending=True)
df

,app,func,end_timestamp,duration,arrival_time,arrival_time_fix
0,7b2c43a2bc30f6bb438074df88b603d2cb982d3e7961de...,e3cdb48830f66eb8689cc0223514569a69812b77e6611e...,7.949090e-02,0.078,1.490900e-03,0.000000e+00
1,1573b95c039e51cc012b543a4af3bc7c3ee9485acbb003...,337cd24a7d5fd5c92460faee4ebe6a186a0eb322bd17b7...,5.715786e+01,57.154,3.860041e-03,2.369141e-03
2,1573b95c039e51cc012b543a4af3bc7c3ee9485acbb003...,48cc770d590d3c5a7691b3b4e9302f82ec3be5ddc2a037...,5.913048e+01,59.125,5.477905e-03,3.987005e-03
3,f274d71de386ccc77e4ca74766dbc485461c3053059d47...,3d2aee54a133509f16fb636d74128c2adcfcac71c6dcef...,6.252541e+00,6.236,1.654107e-02,1.505017e-02
4,7b2c43a2bc30f6bb438074df88b603d2cb982d3e7961de...,68bbfd828223a505d7917339f4656c5f33ff93225cdb9d...,6.682396e-02,0.050,1.682396e-02,1.533306e-02
...,...,...,...,...,...,...
1980946,a594f92f84072b4cd031fe5283d1781a6e98f430696dec...,155e47f8e7f751d0c845049456d01832013c61336a8cd8...,1.209597e+06,0.001,1.209597e+06,1.209597e+06
1980947,a594f92f84072b4cd031fe5283d1781a6e98f430696dec...,155e47f8e7f751d0c845049456d01832013c61336a8cd8...,1.209598e+06,0.001,1.209598e+06,1.209598e+06
1980948,a594f92f84072b4cd031fe5283d1781a6e98f430696dec...,155e47f8e7f751d0c845049456d01832013c61336a8cd8...,1.209599e+06,0.001,1.209599e+06,1.209599e+06
1980949,a594f92f84072b4cd031fe5283d1781a6e98f430696dec...,155e47f8e7f751d0c845049456d01832013c61336a8cd8...,1.209599e+06,0.001,1.209599e+06,1.209599e+06
1980950,a594f92f84072b4cd031fe5283d1781a6e98f430696dec...,155e47f8e7f751d0c845049456d01832013c61336a8cd8...,1.209600e+06,0.001,1.209600e+06,1.209600e+06

In [5]:
# Step 1: Round up the arrival time
df['arrival_time_ceil'] = np.ceil(df['arrival_time']).astype(int)

# Step 2: Group by 'func' and 'arrival_time_ceil' and count
grouped = df.groupby(['func', 'arrival_time_ceil']).size()

# Step 3: Find the maximum count per function
max_per_func = grouped.groupby('func').max()
max_per_func = max_per_func.sort_values(ascending=False)


max_per_func

func
30aa434528bc68ee07745ee7be3a0bdb33d58961fdc8460ce5b5b46b4def96e8    190
7b80f728977125eae11985352adfe15333616e63075c3a14e057745b550b25ac    100
f781a67e39fc1fed1490db6798862355be27cdcf6b7b1d87a38b334db073659c     82
d4aba3f5df4003cfe6f1b8c1c4401f65a8367c37855103ca5911fc7d1bccf47b     69
41630cdded05ac1d73e45a72ff07c22e90fe6b1d537c5825377a983998c05ad0     69
                                                                   ...
6643b31ab35f564d8483ae292d9da3840cb87fcfd928f8e8c03671e1541654f3      1
660b6496a8cb2d3733a1ab71bc0cefe7d9128e5606b4bb2729c7e7f51f72f281      1
649660c7bc3d9fb06c81efa45c90c72edc8906659c581018dd6af054d5f098da      1
61ef4300ea0cf81d4602407705b6f30e159f089deb27d5088e620cdfebe0ba7b      1
fffac43a8d613c58f12b2f63e20c02949f946117af39318fc99649f16331cd5c      1
Length: 424, dtype: int64

In [23]:
f_path = "../dataset/functions.csv"
func = pd.read_csv(f_path)

,id,func,path,docker,memory
0,313c03f53a0d31f70aec25f62efb33e7dd779725ca4af5...,alexnet,alexnet.py,pandeymanish93/ml-inference:alexnet-v1.0,1024
1,556ccf8758c8c2a20082c161e955405e950439f0503522...,resnet50,resnet50.py,pandeymanish93/ml-inference:resnet50-v1.0,1024
2,155e47f8e7f751d0c845049456d01832013c61336a8cd8...,googlenet,googlenet.py,pandeymanish93/ml-inference:googlenet-v1.0,1024
3,31aa5ab69d7730086b08f4303aa2ac3244c639866908fc...,bert,bert.py,pandeymanish93/ml-inference:bert-v1.0,1024
4,426930ee2324a425c25463ff35403f47f2f86624df705f...,distilgpt2,distilgpt2.py,pandeymanish93/ml-inference:distilgpt2-v1.0,1024
5,b74c4ab0e0a6349700abbf5ca5f97d54005710f2289f96...,inception,inception.py,andeymanish93/ml-inference:inception-v1.0,1024
6,9bc86d6cd1ee254aaa313492f0fd88be8bd7b92d50d423...,efficientnet,efficientnet.py,docker=pandeymanish93/ml-inference:efficientne...,1024

In [21]:
df[(df['func'] == '9bc86d6cd1ee254aaa313492f0fd88be8bd7b92d50d4237ff52d7685440c0906') & 
   (df['arrival_time_ceil'] < 14400)]

,app,func,end_timestamp,duration,arrival_time,arrival_time_fix,arrival_time_ceil
40,7fa05b607ae861b85ec53cea12d3efaed8be0f9a92f5d6...,9bc86d6cd1ee254aaa313492f0fd88be8bd7b92d50d423...,72.787311,38.983,33.804311,33.802820,34
44,7fa05b607ae861b85ec53cea12d3efaed8be0f9a92f5d6...,9bc86d6cd1ee254aaa313492f0fd88be8bd7b92d50d423...,116.753216,43.928,72.825216,72.823725,73
47,7fa05b607ae861b85ec53cea12d3efaed8be0f9a92f5d6...,9bc86d6cd1ee254aaa313492f0fd88be8bd7b92d50d423...,155.936031,39.151,116.785031,116.783540,117
54,7fa05b607ae861b85ec53cea12d3efaed8be0f9a92f5d6...,9bc86d6cd1ee254aaa313492f0fd88be8bd7b92d50d423...,186.990186,30.991,155.999186,155.997695,156
60,7fa05b607ae861b85ec53cea12d3efaed8be0f9a92f5d6...,9bc86d6cd1ee254aaa313492f0fd88be8bd7b92d50d423...,225.940778,38.909,187.031778,187.030287,188
...,...,...,...,...,...,...,...
16992,7fa05b607ae861b85ec53cea12d3efaed8be0f9a92f5d6...,9bc86d6cd1ee254aaa313492f0fd88be8bd7b92d50d423...,14286.802703,33.885,14252.917703,14252.916212,14253
17020,7fa05b607ae861b85ec53cea12d3efaed8be0f9a92f5d6...,9bc86d6cd1ee254aaa313492f0fd88be8bd7b92d50d423...,14328.095395,41.251,14286.844395,14286.842904,14287
17089,7fa05b607ae861b85ec53cea12d3efaed8be0f9a92f5d6...,9bc86d6cd1ee254aaa313492f0fd88be8bd7b92d50d423...,14373.004268,44.807,14328.197268,14328.195777,14329
17141,7fa05b607ae861b85ec53cea12d3efaed8be0f9a92f5d6...,9bc86d6cd1ee254aaa313492f0fd88be8bd7b92d50d423...,14396.308289,23.267,14373.041289,14373.039798,14374
17143,7fa05b607ae861b85ec53cea12d3efaed8be0f9a92f5d6...,9bc86d6cd1ee254aaa313492f0fd88be8bd7b92d50d423...,14436.230239,39.868,14396.362239,14396.360748,14397

In [33]:
result = {}
for _, row in func.iterrows():
    count = df[(df['func'] == row['id']) & 
           (df['arrival_time_ceil'] >= 14400)].shape[0]
    result[row['func']] = count

In [34]:
result

{'alexnet': 11506,
 'resnet50': 5293,
 'googlenet': 526700,
 'bert': 4351,
 'distilgpt2': 550,
 'inception': 3637,
 'efficientnet': 4790}