In [82]:
import sqlite3
import pandas as pd
import json
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import Rectangle
import numpy as np
import seaborn as sns
import json
# Connect to the database
conn = sqlite3.connect("../database.db")
cursor = conn.cursor()

In [83]:
# for profiling 
# experiment_no = "results/profiling/2025-04-10_17-45-03.csv"
filename = "2025-04-11_16-21-48.csv"
experiment_no = "results/profiling/"+filename
key= "resnet50"+"_"+"gpu"+"_"+"False"
params={"filename": filename,"key":key}

In [84]:
# Execute the query
cursor.execute(
    "SELECT results FROM profiling WHERE filename = :filename AND key = :key",
    params
)

# Fetch results
row = cursor.fetchone()
result = json.loads(row[0])
result

{'status': 'success',
 'result': [{'index': 282, 'class': 'tiger cat', 'confidence': 0.7101}],
 'system_stats_before': {'cpu_usage_percent': 9.5,
  'memory_used_mb': 4637.38,
  'memory_total_mb': 128720.39,
  'gpus': [{'gpu_index': 0,
    'device': 'NVIDIA GeForce RTX 3090',
    'memory_allocated_mb': 0.0,
    'memory_reserved_mb': 0.0,
    'total_memory_mb': 24154.38},
   {'gpu_index': 1,
    'device': 'NVIDIA GeForce RTX 3090',
    'memory_allocated_mb': 0.0,
    'memory_reserved_mb': 0.0,
    'total_memory_mb': 24154.38}]},
 'system_stats_after': {'cpu_usage_percent': 4.7,
  'memory_used_mb': 4963.57,
  'memory_total_mb': 128720.39,
  'gpus': [{'gpu_index': 0,
    'device': 'NVIDIA GeForce RTX 3090',
    'memory_allocated_mb': 189.39,
    'memory_reserved_mb': 218.0,
    'total_memory_mb': 24154.38},
   {'gpu_index': 1,
    'device': 'NVIDIA GeForce RTX 3090',
    'memory_allocated_mb': 0.0,
    'memory_reserved_mb': 0.0,
    'total_memory_mb': 24154.38}]},
 'measurement': {'lib_load_start': 1744356136201,
  'lib_load_end': 1744356137429,
  'model_load_start': 1744356137527,
  'model_load_end': 1744356137772,
  'image_load_start': 1744356137516,
  'image_load_end': 1744356137527,
  'gpu_transfer_start': 1744356137772,
  'gpu_transfer_end': 1744356137910,
  'preprocess_start': 1744356137910,
  'preprocess_end': 1744356137914,
  'inference_start': 1744356137914,
  'inference_end': 1744356138078,
  'output_start': 1744356138078,
  'output_end': 1744356138090}}

{'cpu_usage_percent': 6.6,
 'memory_used_mb': 4009.71,
 'memory_total_mb': 128720.39,
 'gpus': [{'gpu_index': 0,
   'device': 'NVIDIA GeForce RTX 3090',
   'memory_allocated_mb': 80.12,
   'memory_reserved_mb': 82.0,
   'total_memory_mb': 24154.38},
  {'gpu_index': 1,
   'device': 'NVIDIA GeForce RTX 3090',
   'memory_allocated_mb': 0.0,
   'memory_reserved_mb': 0.0,
   'total_memory_mb': 24154.38}]}

In [66]:
def total_gpu_memory(gpus):
    total = 0.0
    for gpu in gpus:
        total += gpu['memory_allocated_mb']
    return total

In [67]:
gpu_memory_before = total_gpu_memory(before['gpus'])
gpu_memory_before

NameError: name 'before' is not defined

In [33]:
df = pd.read_csv('../'+experiment_no)

,id,filename,key,test_config,results
0,86,2025-04-11_10-39-39.csv,distilgpt2_cpu_False,"{""device"": ""cpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""output"": ""'''Python fun..."
1,87,2025-04-11_10-39-39.csv,bert_cpu_False,"{""device"": ""cpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""output"": ""The capital o..."
2,88,2025-04-11_10-39-39.csv,alexnet_cpu_False,"{""device"": ""cpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""result"": [{""index"": 282..."
3,89,2025-04-11_10-39-39.csv,resnet50_cpu_False,"{""device"": ""cpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""result"": [{""index"": 282..."
4,90,2025-04-11_10-39-39.csv,googlenet_cpu_False,"{""device"": ""cpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""result"": [{""index"": 282..."
5,91,2025-04-11_10-39-39.csv,efficientnet_cpu_False,"{""device"": ""cpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""result"": [{""index"": 282..."
6,92,2025-04-11_10-39-39.csv,inception_cpu_False,"{""device"": ""cpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""result"": [{""index"": 282..."
7,93,2025-04-11_10-39-39.csv,distilgpt2_gpu_False,"{""device"": ""gpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""output"": ""'''Python fun..."
8,94,2025-04-11_10-39-39.csv,bert_gpu_False,"{""device"": ""gpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""output"": ""The capital o..."
9,95,2025-04-11_10-39-39.csv,alexnet_gpu_False,"{""device"": ""gpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""result"": [{""index"": 282..."
10,96,2025-04-11_10-39-39.csv,resnet50_gpu_False,"{""device"": ""gpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""result"": [{""index"": 282..."
11,97,2025-04-11_10-39-39.csv,googlenet_gpu_False,"{""device"": ""gpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""result"": [{""index"": 282..."
12,98,2025-04-11_10-39-39.csv,efficientnet_gpu_False,"{""device"": ""gpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""result"": [{""index"": 282..."
13,99,2025-04-11_10-39-39.csv,inception_gpu_False,"{""device"": ""gpu"", ""multi_gpu"": false, ""local"":...","{""status"": ""success"", ""result"": [{""index"": 282..."
14,100,2025-04-11_10-39-39.csv,alexnet_gpu_True,"{""device"": ""gpu"", ""multi_gpu"": true, ""local"": ...","{""status"": ""success"", ""result"": [{""index"": 282..."
15,101,2025-04-11_10-39-39.csv,resnet50_gpu_True,"{""device"": ""gpu"", ""multi_gpu"": true, ""local"": ...","{""status"": ""success"", ""result"": [{""index"": 282..."
16,102,2025-04-11_10-39-39.csv,googlenet_gpu_True,"{""device"": ""gpu"", ""multi_gpu"": true, ""local"": ...","{""status"": ""success"", ""result"": [{""index"": 282..."
17,103,2025-04-11_10-39-39.csv,efficientnet_gpu_True,"{""device"": ""gpu"", ""multi_gpu"": true, ""local"": ...","{""status"": ""success"", ""result"": [{""index"": 282..."
18,104,2025-04-11_10-39-39.csv,inception_gpu_True,"{""device"": ""gpu"", ""multi_gpu"": true, ""local"": ...","{""status"": ""success"", ""result"": [{""index"": 282..."

In [26]:
df

   device  multi_gpu  local  batch_size  latency         model
0     cpu      False   True           1     3261    distilgpt2
1     cpu      False   True           1     3037          bert
2     cpu      False   True           1     2071       alexnet
3     cpu      False   True           1     2007      resnet50
4     cpu      False   True           1     1855     googlenet
5     cpu      False   True           1     2601  efficientnet
6     cpu      False   True           1     2099     inception
7     gpu      False   True           1     3191    distilgpt2
8     gpu      False   True           1     2965          bert
9     gpu      False   True           1     2119       alexnet
10    gpu      False   True           1     1995      resnet50
11    gpu      False   True           1     1840     googlenet
12    gpu      False   True           1     2683  efficientnet
13    gpu      False   True           1     2140     inception
14    gpu       True   True           1     2056       alexnet
15    gpu       True   True           1     1982      resnet50
16    gpu       True   True           1     1818     googlenet
17    gpu       True   True           1     2649  efficientnet
18    gpu       True   True           1     2105     inception

In [27]:
df[df['model']=='resnet50']

   device  multi_gpu  local  batch_size  latency     model
3     cpu      False   True           1     2007  resnet50
10    gpu      False   True           1     1995  resnet50
15    gpu       True   True           1     1982  resnet50